### ISSUE TITLE
Add option to client only webapp

### ISSUE THREAD

**Issue by skodapetr** [MarkSeliverstov/MFF-bachelor-work#12]
We can add a build option, or even build target (separate entry point) where instead of fetching the files from a URL, user would need to [provide inputs files](https://quasar.dev/vue-components/file) (annotations, entities) from their computer.

As a result it would be possible to deploy the web-application as a static website. Of course this deployment would errored when user try to open entity using query arguments. 

Another options, they can be implemented simultaneously, is to set URL for annotations and entities files using query arguments. That should be easy to do.

**Comment by MarkSeliverstov** [comment]
Done by defining urls in different envs
