### ISSUE TITLE
Consider removal of parserInclude option

### ISSUE THREAD

**Issue by skodapetr** [MarkSeliverstov/MFF-bachelor-work#6]
We already have parserExclude which allows us to exclude what we do not want to parse. I believe this is sufficient and aligned with other tools.

What is the motivation that I need to explicitly white-list files?

EDIT: I would rather consider like an array of patters so I could for example select only files with certain extension and ignore all others.

**Comment by MarkSeliverstov** [comment]
Left only exclude parameter
